 $(document).ready(function () {
                $("#nanoGallery4").nanoGallery({thumbnailWidth: 175, thumbnailHeight: 175,
                    items: [
                        
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'album 1',
                            ID: 103, kind: 'album'},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_03ts.jpg', title: 'album 2',
                            ID: 104, kind: 'album'},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'album 3',
                            ID: 105,  kind: 'album'},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 03',
                            ID: 4, albumID: 103},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 04',
                            ID: 5, albumID: 103},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 05',
                            ID: 6, albumID: 103},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 06',
                            ID: 7, albumID: 103},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 07',
                            ID: 8, albumID: 103},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 08',
                            ID: 9, albumID: 103},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 09',
                            ID: 10, albumID: 103},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 10',
                            ID: 11, albumID: 103},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 10',
                            ID: 12, albumID: 104},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 11',
                            ID: 13, albumID: 104},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 12',
                            ID: 14, albumID: 104},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 13',
                            ID: 15, albumID: 104},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 14',
                            ID: 16, albumID: 105},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 15',
                            ID: 17, albumID: 105},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 16',
                            ID: 18, albumID: 105},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 17',
                            ID: 19, albumID: 105},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 18',
                            ID: 20, albumID: 105},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 19',
                            ID: 21, albumID: 105},
                        {src: 'demonstration/image_02.jpg', srct: 'demonstration/image_02ts.jpg', title: 'image 20',
                            ID: 22, albumID: 105},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 1a',
                            ID: 23, albumID: 103},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 1b',
                            ID: 24, albumID: 103},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 1c',
                            ID: 25, albumID: 103},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 1d',
                            ID: 26, albumID: 103},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 1e',
                            ID: 27, albumID: 103},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 1f',
                            ID: 28, albumID: 103},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 2a',
                            ID: 29, albumID: 104},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 2b',
                            ID: 30, albumID: 104},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 2c',
                            ID: 31, albumID: 104},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 2d',
                            ID: 32, albumID: 104},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 2e',
                            ID: 33, albumID: 104},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 2f',
                            ID: 34, albumID: 104},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 2g',
                            ID: 35, albumID: 104},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 2h',
                            ID: 36, albumID: 104},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 2i',
                            ID: 37, albumID: 104},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 2j',
                            ID: 38, albumID: 104},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 2k',
                            ID: 39, albumID: 104},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 2l',
                            ID: 40, albumID: 104},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 2m',
                            ID: 41, albumID: 104},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 2n',
                            ID: 42, albumID: 104},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 2o',
                            ID: 43, albumID: 104},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 2n',
                            ID: 44, albumID: 105},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 2n',
                            ID: 45, albumID: 105},
                        {src: 'demonstration/image_03.jpg', srct: 'demonstration/image_03ts.jpg', title: 'image 2o',
                            ID: 46, albumID: 105}
                    ]
                });
            });